# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96feadae30c6132c01f80adf041c31fe7bf400fa932e6c89fbcd04a9c13170494a406511e6a2cb8024bde05712274aaf202d6b725be413a5147bc899ab3f89df

test:
  secret_key_base: a8545a2a6a7fe1fcd18179e844b2f137ffdedb69d789d999a51b010b737203a946da82d4318e32ad46bad81c317b10a68ec244bfe278b731bbf6732cf626862e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
